#!/usr/bin/env python3

import argparse
import csv
from collections import OrderedDict
from pathlib import Path


def parse_args():
    script_dir = Path(__file__).resolve().parent
    default_input = script_dir / "output" / "coverage_1b_all_cases.csv"
    default_outdir = script_dir / "output"

    parser = argparse.ArgumentParser(
        description="Create Pattern x ECC ratio tables for CE, DUE, and SDC."
    )
    parser.add_argument(
        "--input",
        default=str(default_input),
        help="Input coverage CSV generated by run.sh",
    )
    parser.add_argument(
        "--outdir",
        default=str(default_outdir),
        help="Directory for generated ratio tables",
    )
    parser.add_argument(
        "--precision",
        type=int,
        default=6,
        help="Number of digits after the decimal point",
    )
    return parser.parse_args()


def load_rows(csv_path):
    with open(csv_path, newline="") as f:
        reader = csv.DictReader(f)
        required = {"ECC", "Pattern", "CE", "DUE", "SDC", "Trials"}
        missing = required.difference(reader.fieldnames or [])
        if missing:
            missing_list = ", ".join(sorted(missing))
            raise ValueError(f"Missing required columns: {missing_list}")

        rows = []
        for row in reader:
            trials = int(row["Trials"])
            rows.append(
                {
                    "ECC": row["ECC"],
                    "Pattern": row["Pattern"],
                    "CE": int(row["CE"]),
                    "DUE": int(row["DUE"]),
                    "SDC": int(row["SDC"]),
                    "Trials": trials,
                }
            )
    return rows


def unique_in_order(rows, key):
    ordered = OrderedDict()
    for row in rows:
        ordered.setdefault(row[key], None)
    return list(ordered.keys())


def build_ratio_table(rows, metric, eccs, patterns):
    table = {}
    for pattern in patterns:
        table[pattern] = {}

    for row in rows:
        trials = row["Trials"]
        ratio = 0.0 if trials == 0 else row[metric] / trials
        table[row["Pattern"]][row["ECC"]] = ratio

    return table


def write_table(path, metric, eccs, patterns, table, precision):
    fmt = "{:." + str(precision) + "f}"
    with open(path, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Pattern", *eccs])
        for pattern in patterns:
            row = [pattern]
            for ecc in eccs:
                value = table[pattern].get(ecc)
                row.append("" if value is None else fmt.format(value))
            writer.writerow(row)


def main():
    args = parse_args()
    input_path = Path(args.input).resolve()
    outdir = Path(args.outdir).resolve()
    outdir.mkdir(parents=True, exist_ok=True)

    rows = load_rows(input_path)
    eccs = unique_in_order(rows, "ECC")
    patterns = unique_in_order(rows, "Pattern")

    for metric in ("CE", "DUE", "SDC"):
        table = build_ratio_table(rows, metric, eccs, patterns)
        out_path = outdir / f"{metric.lower()}_ratio_table.csv"
        write_table(out_path, metric, eccs, patterns, table, args.precision)
        print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
